# 파이토치 기본

In [2]:
import torch
import numpy as np

print(torch.__version__)
print(torch.cuda.is_available())

1.11.0
True


## 1. 텐서

### 1-1. 여러가지 텐서

In [3]:
# 빈 텐서 생성 - 초기화되지 않으면 해당 시점에 할당된 메모리에 존재하던 값이 들어감 
x1 = torch.empty(5,4)
print('x1 : ',x1,'\n')

# 1로 채워진 텐서 생성 
x2 = torch.ones(3,3)
print('x2 : ',x2,'\n')

# 0으로 채워진 텐서 생성 
x3 = torch.zeros(2,2)
print('x3 : ',x3,'\n')

# 무작위값 텐서 생성 ( 0 ~ 1 사잇값 )
x4 = torch.rand(2,3)
print('x4 : ',x4,'\n')

x1 :  tensor([[0.0000e+00, 1.8337e+31, 2.6302e+20, 6.1949e-04],
        [6.4805e-10, 6.3008e-10, 4.2242e-05, 6.9120e-04],
        [6.9369e-07, 1.0721e-08, 6.4097e-10, 1.4580e-19],
        [1.1495e+24, 3.0956e-18, 1.5099e-07, 4.2007e-05],
        [1.2914e-11, 1.0257e-08, 4.1026e-08, 1.7660e-04]]) 

x2 :  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

x3 :  tensor([[0., 0.],
        [0., 0.]]) 

x4 :  tensor([[0.7768, 0.3540, 0.9174],
        [0.4410, 0.7286, 0.7585]]) 



### 1-2. 리스트, 넘파이 배열 to Tensor

`torch.tensor()`를 통해 tensor로 변환이 가능하며   
`torch.FloatTensor()`나 `torch.LongTensor()`를 통해서도 가능하다. 

In [4]:
l = [13,4]
r = np.array([4,56,7])
print(type(l))
print(type(r))

print('---to tensor---')

l = torch.tensor(l)
r = torch.tensor(r)
print(type(l))
print(type(r))


<class 'list'>
<class 'numpy.ndarray'>
---to tensor---
<class 'torch.Tensor'>
<class 'torch.Tensor'>


### 1-3. 텐서의 크기,타입, 연산

`.size()`는 텐서의 크기를 확인할 때 자주 사용한다.  

텐서의 연산은 넘파이에서의 연산과 매우 비슷하다. 추가적으로 편리한 기능들이 있다. 

In [11]:
print('x1 :',x1,'\n')
print('x1 size :',x1.size(),'\n')
print('x1 type :',type(x1))

x1 : tensor([[0.0000e+00, 1.8337e+31, 2.6302e+20, 6.1949e-04],
        [6.4805e-10, 6.3008e-10, 4.2242e-05, 6.9120e-04],
        [6.9369e-07, 1.0721e-08, 6.4097e-10, 1.4580e-19],
        [1.1495e+24, 3.0956e-18, 1.5099e-07, 4.2007e-05],
        [1.2914e-11, 1.0257e-08, 4.1026e-08, 1.7660e-04]]) 

x1 size : torch.Size([5, 4]) 

x1 type : <class 'torch.Tensor'>


In [24]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [25]:
# 아래 방법 모두 같은 결과를 return 함 
print(x + y)
print(torch.add(x,y))
print(y.add(x)) 

tensor([[0.5897, 0.3523],
        [1.5219, 1.0029]])
tensor([[0.5897, 0.3523],
        [1.5219, 1.0029]])
tensor([[0.5897, 0.3523],
        [1.5219, 1.0029]])


In [26]:
# .함수_()의 형태로 사용하면 함수를 수행하고 .앞의(왼쪽의) 객체에 결과값을 저장하여 반환한다. 
y.add_(x)
print(y)

tensor([[0.5897, 0.3523],
        [1.5219, 1.0029]])


### 1-4. 텐서의 크기 변환

In [30]:
x = torch.rand(8,8)
print(x.shape)
print(x.size())
print(x)

torch.Size([8, 8])
torch.Size([8, 8])
tensor([[0.9417, 0.8784, 0.7666, 0.5513, 0.2317, 0.9880, 0.7830, 0.2894],
        [0.5370, 0.1044, 0.2566, 0.8592, 0.8769, 0.4383, 0.1077, 0.5775],
        [0.7729, 0.2749, 0.1776, 0.1732, 0.4010, 0.7537, 0.2399, 0.2734],
        [0.8536, 0.2177, 0.4392, 0.0386, 0.3541, 0.2022, 0.5426, 0.7451],
        [0.9505, 0.5393, 0.9083, 0.2313, 0.1524, 0.3411, 0.3587, 0.5621],
        [0.5288, 0.1073, 0.0809, 0.0274, 0.1622, 0.4711, 0.9259, 0.8360],
        [0.5212, 0.5250, 0.2365, 0.9296, 0.6929, 0.1263, 0.3124, 0.5648],
        [0.0171, 0.4686, 0.8744, 0.1601, 0.5393, 0.6007, 0.2609, 0.6567]])


In [34]:
a = x.view(64) # 8 x 8 -> 64
print(a.size())

b = x.view(-1,4,4) # -1은 알맞는 값으로 알아서 채워줌 
print(b.size())

torch.Size([64])
torch.Size([4, 4, 4])


### 1-5. 텐서에서 넘파이 배열로 변환 

`.numpy()`를 이용하여 텐서를 넘파이 배열로 변환 가능하다. 

In [36]:
x = torch.rand(8,8)
print(type(x))
y = x.numpy()
print(type(y))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### 1-6. 단일 텐서(1,)에서 값으로 반환하기

`.item()`을 사용하여 size가 (1,)인 텐서에서 스칼라값을 추출해 준다. 

In [40]:
x = torch.ones(1)
print(x)
print(x.item())

tensor([1.])
1.0


## 2. 역전파 

### 2-1. Gradient Tensor 

